myprop.name=Myspring_homework

#log level : info
logging.level.com.example.Myspring_homework=info

#hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
